
openai_api_key: #INSERT OPEN AI API KEY HERE

cogvlm2_host_ip: #INSERT CogVLM2 HOST IP ADDRESS HERE
cogvlm2_port: #INSERT CogVLM2 PORT NUMBER

cogvlm_host_ip: #INSERT CogVLM HOST IP ADDRESS HERE
cogvlm_port: #INSERT CogVLM PORT NUMBER

pipeline_path: #INSERT PATH TO THIS DIRECTORY HERE

dataset_folder: #INSERT THE PATH TO THE DOWNLOADED DATASET HERE

server_video_path: #INSERT VIDEO PATH ON THE SERVER SIDE HERE

baseline_number: #INSERT THE BASELINE NUMBER. 1-DIRECT TEMPORAL VISUAL GROUNDING, 2-REFINED TEMPORAL VISUAL GROUNDING