#OpenAI API Key

openai_api_key: #INSERT OPENAI API KEY HERE

#CogVLM2: host, port no.
cogvlm2_host_ip: #INSERT CogVLM2 HOST IP ADDRESS HERE
cogvlm2_port: #INSERT CogVLM2 PORT NUMBER

#SAM2: host, port no.
sam2_host_ip: #INSERT SAM2 HOST IP ADDRESS HERE
sam2_port: #INSERT SAM2 PORT NUMBER 

# main pipeline path 
pipeline_path: #INSERT PIPELINE PATH HERE

# Length of recorded action video
video_length: 5

#Dataset Path
dataset_folder_path: #DOWNLOAD DATASET FROM DATASET LINK AND INSERT IT HERE
