#OpenAI API Key

openai_api_key: "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"

#host, port no.

host_ip: "10.237.23.193"
port: 65440

# Output folder path

output_folder_path: "/home/nivi_nath/tmp_reason_ws/src/driver_codes/fm_temporal_reasoning/output/run_output/"

# main pipeline path 

pipeline_path: '/home/nivi_nath/tmp_reason_ws/src/driver_codes/fm_temporal_reasoning/'

# Length of recorded action video

video_length: 5