#OpenAI API Key

openai_api_key: "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"

#host, port no.

host_ip: "10.237.23.193"
port: 65439


#width, height of frames
width: 640
height: 480

#

openai_model: ""

